
//gitlab的凭证-9047bf42-b6da-425a-9783-d4d7c69f0290

def git_auth = "4893aefe-5aeb-4c30-8ee8-76abd7797610"


def tag = "latest"

def project_name = "jenkins"

node {
	stage('拉取代码') {
	    sh "echo *******开始拉取代码*********"
		checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '9047bf42-b6da-425a-9783-d4d7c69f0290', url: 'https://github.com/guojun5642940/jenkins.git']]])
	    sh "echo *******代码拉取结束*********"
	}

	stage('编译，构建镜像') {

	    sh 'docker ps -f name=runningJenkins -q | xargs --no-run-if-empty docker container stop'

        sh 'docker container ls -a -fname=runningJenkins -q | xargs -r docker container rm'

		sh "mvn package -Dmaven.test.skip=true docker:build"

		sh "docker run -d -p:8081:8081 --name runningJenkins  ${harbor_url}/${project_name}:${tag}"
	}
}